### ISSUE TITLE
Transferring to S3, but not correctly changing URL

### ISSUE THREAD

**Issue by TraciBunkers** [sanbornmedia/wordpress-amazon-s3-plugin#4]
I'm having an odd issue where the plugin does upload & transfer the image to my S3 bucket, but it's not changing the image URL to my cloudfront URL. Instead, it's adding an extra "blog/" to the path and keeping my domain instead of changing it to cloudfront. In the plugin settings, I've got the path as blog/wp-content/uploads. And it's changing the URL to http://www.MY-SITE.com/blog/blog/wp-content/uploads/2014/03/IMAGE.jpg. BUT, the image is in my S3 bucket with the path of MY-BUCKET/blog/wp-content/uploads/2014/03/IMAGE.jpg.

If I delete blog/ from my path in the settings, then it uploads to S3 1 level up: MY-BUCKET/wp-content/uploads/2014/03/IMAGE.jpg and it keeps the image URL at http://www.MY-SITE.com/blog/wp-content/uploads/2014/03/IMAGE.jpg

I've got a test blog set up on the same server & domain, but different WP install & database. The plugin works fine there. But on with my main blog if I deactivate all the plugins except this one & change my theme to the default theme to replicate my test blog setup, I still have the exact same problems.

Any ideas what's going on? Is there something in my database I need to look for that could be causing the problem?

**Comment by jhampton** [comment]
URL Rewrites happen on-the-fly – take a look at the code.  It sounds like there might be something going on in your theme or config somewhere messing with that path.
